server:
  port: 8080
  mode: debug          # release/test

mysql:
  dsn: "user:pass@tcp(127.0.0.1:3306)/go_star?charset=utf8mb4&parseTime=true&loc=Local"
  max_open_conns: 50          # 连接池最大打开连接数
  max_idle_conns: 25          # 连接池最大空闲连接数
  max_lifetime: "1h"          # 连接最大生命周期
  slow_threshold: "500ms"     # 慢查询阈值
  log_level: "info"           # gorm 日志级别：silent / error / warn / info

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
  pool_size: 20

jwt:
  secret: "supersecret"
  expire: 24h

log:
  level: info
  format: json